/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardAnalisisRouteImport } from './routes/dashboard/analisis'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotRouteImport } from './routes/_auth/forgot'
import { Route as DashboardFinanzasRecurrentesRouteImport } from './routes/dashboard/finanzas/recurrentes'
import { Route as DashboardFinanzasPresupuestosRouteImport } from './routes/dashboard/finanzas/presupuestos'
import { Route as DashboardConfigCuentasRouteImport } from './routes/dashboard/config/cuentas'
import { Route as DashboardConfigCategoriasRouteImport } from './routes/dashboard/config/categorias'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalisisRoute = DashboardAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/_auth/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFinanzasRecurrentesRoute =
  DashboardFinanzasRecurrentesRouteImport.update({
    id: '/finanzas/recurrentes',
    path: '/finanzas/recurrentes',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFinanzasPresupuestosRoute =
  DashboardFinanzasPresupuestosRouteImport.update({
    id: '/finanzas/presupuestos',
    path: '/finanzas/presupuestos',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardConfigCuentasRoute = DashboardConfigCuentasRouteImport.update({
  id: '/config/cuentas',
  path: '/config/cuentas',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfigCategoriasRoute =
  DashboardConfigCategoriasRouteImport.update({
    id: '/config/categorias',
    path: '/config/categorias',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/profile': typeof ProfileRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analisis': typeof DashboardAnalisisRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/config/categorias': typeof DashboardConfigCategoriasRoute
  '/dashboard/config/cuentas': typeof DashboardConfigCuentasRoute
  '/dashboard/finanzas/presupuestos': typeof DashboardFinanzasPresupuestosRoute
  '/dashboard/finanzas/recurrentes': typeof DashboardFinanzasRecurrentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/profile': typeof ProfileRoute
  '/forgot': typeof AuthForgotRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analisis': typeof DashboardAnalisisRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/config/categorias': typeof DashboardConfigCategoriasRoute
  '/dashboard/config/cuentas': typeof DashboardConfigCuentasRoute
  '/dashboard/finanzas/presupuestos': typeof DashboardFinanzasPresupuestosRoute
  '/dashboard/finanzas/recurrentes': typeof DashboardFinanzasRecurrentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/profile': typeof ProfileRoute
  '/_auth/forgot': typeof AuthForgotRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/analisis': typeof DashboardAnalisisRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/config/categorias': typeof DashboardConfigCategoriasRoute
  '/dashboard/config/cuentas': typeof DashboardConfigCuentasRoute
  '/dashboard/finanzas/presupuestos': typeof DashboardFinanzasPresupuestosRoute
  '/dashboard/finanzas/recurrentes': typeof DashboardFinanzasRecurrentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/dashboard/analisis'
    | '/dashboard/overview'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/config/categorias'
    | '/dashboard/config/cuentas'
    | '/dashboard/finanzas/presupuestos'
    | '/dashboard/finanzas/recurrentes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/forgot'
    | '/login'
    | '/signup'
    | '/api/health'
    | '/dashboard/analisis'
    | '/dashboard/overview'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/config/categorias'
    | '/dashboard/config/cuentas'
    | '/dashboard/finanzas/presupuestos'
    | '/dashboard/finanzas/recurrentes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/_auth/forgot'
    | '/_auth/login'
    | '/_auth/signup'
    | '/api/health'
    | '/dashboard/analisis'
    | '/dashboard/overview'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/config/categorias'
    | '/dashboard/config/cuentas'
    | '/dashboard/finanzas/presupuestos'
    | '/dashboard/finanzas/recurrentes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analisis': {
      id: '/dashboard/analisis'
      path: '/analisis'
      fullPath: '/dashboard/analisis'
      preLoaderRoute: typeof DashboardAnalisisRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot': {
      id: '/_auth/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/finanzas/recurrentes': {
      id: '/dashboard/finanzas/recurrentes'
      path: '/finanzas/recurrentes'
      fullPath: '/dashboard/finanzas/recurrentes'
      preLoaderRoute: typeof DashboardFinanzasRecurrentesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finanzas/presupuestos': {
      id: '/dashboard/finanzas/presupuestos'
      path: '/finanzas/presupuestos'
      fullPath: '/dashboard/finanzas/presupuestos'
      preLoaderRoute: typeof DashboardFinanzasPresupuestosRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/config/cuentas': {
      id: '/dashboard/config/cuentas'
      path: '/config/cuentas'
      fullPath: '/dashboard/config/cuentas'
      preLoaderRoute: typeof DashboardConfigCuentasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/config/categorias': {
      id: '/dashboard/config/categorias'
      path: '/config/categorias'
      fullPath: '/dashboard/config/categorias'
      preLoaderRoute: typeof DashboardConfigCategoriasRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAnalisisRoute: typeof DashboardAnalisisRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardConfigCategoriasRoute: typeof DashboardConfigCategoriasRoute
  DashboardConfigCuentasRoute: typeof DashboardConfigCuentasRoute
  DashboardFinanzasPresupuestosRoute: typeof DashboardFinanzasPresupuestosRoute
  DashboardFinanzasRecurrentesRoute: typeof DashboardFinanzasRecurrentesRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalisisRoute: DashboardAnalisisRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardConfigCategoriasRoute: DashboardConfigCategoriasRoute,
  DashboardConfigCuentasRoute: DashboardConfigCuentasRoute,
  DashboardFinanzasPresupuestosRoute: DashboardFinanzasPresupuestosRoute,
  DashboardFinanzasRecurrentesRoute: DashboardFinanzasRecurrentesRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ProfileRoute: ProfileRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
